export const DIFF_DOCS_FETCH_MERGE_BEGIN = 'DIFF_DOCS_FETCH_MERGE_BEGIN';
export const DIFF_DOCS_FETCH_MERGE_SUCCESS = 'DIFF_DOCS_FETCH_MERGE_SUCCESS';
export const DIFF_DOCS_FETCH_MERGE_FAILURE = 'DIFF_DOCS_FETCH_MERGE_FAILURE';
export const DIFF_DOCS_FETCH_MERGE_DISMISS_ERROR = 'DIFF_DOCS_FETCH_MERGE_DISMISS_ERROR';
