export const UPLOAD_FILE_FETCH_MERGE_BEGIN = 'UPLOAD_FILE_FETCH_MERGE_BEGIN';
export const UPLOAD_FILE_FETCH_MERGE_SUCCESS = 'UPLOAD_FILE_FETCH_MERGE_SUCCESS';
export const UPLOAD_FILE_FETCH_MERGE_FAILURE = 'UPLOAD_FILE_FETCH_MERGE_FAILURE';
export const UPLOAD_FILE_FETCH_MERGE_DISMISS_ERROR = 'UPLOAD_FILE_FETCH_MERGE_DISMISS_ERROR';
